### PR TITLE
Modify and Test tests.yml

### PR DESCRIPTION
**Pull request by yqiqichen**

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
@XingerTang can you review and show @yqiqichen how to squash commits?

**Comment by XingerTang** [comment]
@gregorgorjanc Sure! It's just that she may need to modify the tests to do some real testing before merging, now it's just a sample test file (I've talked with her about this). I will help her in squashing commits once the tests are done.

**Comment by XingerTang** [comment]
@yqiqichen The pull request should be merged before close or these changes won't be saved in this repository. Are you trying to squash the commits? You could do that within this pull request.

**Comment by yqiqichen** [comment]
@XingerTang Yes. I am trying to squash the commits. I will reopen the pull request. 
Thank you for informing me!

**Comment by XingerTang** [comment]
> @XingerTang Yes. I am trying to squash the commits. I will reopen the pull request. Thank you for informing me!

This is the link I find useful for squashing the commits: https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

Hope you find this helpful.

**Comment by gregorgorjanc** [comment]
Closing this PR in favour of #38

**Pull request closed without merging**
